package halo;

import java.util.*;

// Aggregation is a "has a" relationship meaning it is a one way association
// The child can exist independently of the parent.

// Example: A car performs its functions through the use of an engine
// However, an engine is not always a part of a car.
// An engine can be swapped out or not used.

class Ben extends constructor
{ 
	// Driver method to test above 
    public static void main(String args[]) 
    { 
    	
       Engine engine = new Engine();
       
       
       Car car = new Car(engine);
       car.move();
       
       
       
       
    } 
} 
